In [1]:
import numpy as np
import linalg_tools

In [4]:
#%% Problem 2
# a
A = np.array([[-1, 2, 0],
[5, 1, -2],[6, 3, 4]])
rankA = np.linalg.matrix_rank(A)

# b
B = np. array([[3, 2, 2, -5],
[0.6, 1.5, 1.5, -5.4],
[1.2, -0.3, -0.3, 2.4]])
rankB = np.linalg.matrix_rank(B)

print('The rank of A is ', rankA)
print('The rank of B is ', rankB)

The rank of A is  3
The rank of B is  2


In [5]:
#%% Problem 3
# a
A_augmented = np.array([[2, -1, 3, 0],
[-1, 4, -1, 10],
[0, 10, 15, 50],
[20, 10, 1, 40]])

solutions = linalg_tools.lin_sol(A_augmented)

print('About the first system...')
if solutions == 'unique solution':
    A = A_augmented[0:-1, 0:-1]
    b = A_augmented[0:-1, -1]
    X = np.linalg.solve(A, b)
    print('The solutions are ', X)
else:
    print('The system has ' + solutions + '\n')

# b
A_augmented = np.array([[2, -1, 3, 0],
[-1, 4, -1, 10],
[0, 10, 15, 50],
[20, 10, 1, 40]])

solutions = linalg_tools.lin_sol(A_augmented)

print('About the second system...')

if solutions == 'unique solution':
    A = A_augmented[0:-1, 0:-1]
    b = A_augmented[0:-1, -1]
    X = np.linalg.solve(A, b)
    print('The solutions are ', X)
else:
    print('The system has ' + solutions + '\n')

About the first system...
The system has no solution

About the second system...
The system has no solution



In [ ]:
#%% Problem 4
# a
A = np.array([[-5, 0], [0, 3]])
eigval_A, eigvect_A = np.linalg.eig(A)

# b
B = np.array([[-1, 2], [5, 2]])
eigval_B, eigvect_B = np.linalg.eig(B)

print('The eigenvalues of A are \n', eigval_A)
print('The eigenvectors of A are \n', eigvect_A, '\n')

print('The eigenvalues of A are \n', eigval_B)
print('The eigenvectors of A are \n', eigvect_B, '\n')

In [19]:
#%% Problem 5
# a
A = np.array([[1, -3], [4, 10]])
diag_A, eigvects_A = linalg_tools.diagonalize(A)

# b
B = np.array([[4, 3, 6],
[3, -8, 15],
[6, 15, 10]])
diag_B, eigvects_B = linalg_tools.diagonalize(B)

print('The matrix that diagonalizes A is \n', diag_A, '\n')
print('The matrix that diagonalizes B is \n', diag_B, '\n')

#%% Proof
A_proof = eigvects_A@diag_A@np.linalg.inv(eigvects_A)
print('A proof can be made getting the matrix from diag_matrix \n')
print(A_proof, '\n')

B_proof = eigvects_B@diag_B@np.linalg.inv(eigvects_B)
print('A proof can be made getting the matrix from diag_matrix \n')
print(B_proof, '\n')

The matrix that diagonalizes A is 
 [[2.62771868 0.        ]
 [0.         8.37228132]] 

The matrix that diagonalizes B is 
 [[ 21.11555196   0.           0.        ]
 [  0.           1.38351895   0.        ]
 [  0.           0.         -16.49907091]] 

A proof can be made getting the matrix from diag_matrix 

[[ 1. -3.]
 [ 4. 10.]] 

A proof can be made getting the matrix from diag_matrix 

[[ 4.  3.  6.]
 [ 3. -8. 15.]
 [ 6. 15. 10.]] 

